---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-snow-indexes
  namespace: ibm-aiops-installation
spec:
  serviceAccountName: demo-admin
  template:
    spec:
      containers:
        - name: load
          image: docker.io/niklaushirt/ibm-aiops-tools:2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "1256Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              #set -x

              echo "*****************************************************************************************************************************"
              echo " ✅ STARTING: Load service now training files"
              echo "*****************************************************************************************************************************"

              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              echo "    📥 Downloading service now training files"
              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              export AWX_REPO=https://github.com/niklaushirt/ibm-aiops-trainingdata.git
              git clone $AWX_REPO

              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              echo "    🚀 Starting Data Load"
              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              cd ibm-aiops-trainingdata
              git log|head -n 17
              cd -
              echo ""
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "This Repo includes those latestet Commits"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              cd ibm-aiops-trainingdata
              git log|head -n 17
              cd -
              echo ""
              echo ""
              echo "*****************************************************************************************************************************"
              echo " ✅ DONE"
              echo "*****************************************************************************************************************************"
              sleep 60000

          env:
            - name: INDEX_OVERWRITE
              value : "false"
            - name: VERSION
              value : "3.3"
      restartPolicy: Never

  backoffLimit: 4
